### ISSUE TITLE
Falsche Position von Elementen im Fenster.

### ISSUE THREAD

**Issue by Rotwolf** [weichware10/toolbox#17]
ich habe 3 Bildschirme
1280 x 1024
3840 x 2160
1920 x 1080

öffnen, anmelden (test_admin) und test erstellen funktioniert auf allen Fenstern normal.
Nach drücken auf Start erscheint auf allen fenstern das Intro,
nur auf dem 3840 x 2160 erscheint es nicht in der Mitte, sondern rechts unten.
wenn das Fenster kleiner gemacht wird und danach wieder auf vollbild(Fenster) gestreckt wird ist der Text wieder in der Mitte.

Diese Verschiebung passiert nur auf diesem Monitor & bei jedem Arbeitsschritt ab diesem Moment.
Auch nach newTest beim insertTrailID Fernster. (Wo anfangs ja alles Funktioniert hatte)
Dadurch wird auch das eingeben der Frage unmöglich, da sie sich "unter" dem unterem Rand des Monitors befindet. (Vermute ich)
Deswegen muss ich da im Moment immer das Fenster keiner und wieder groß machen um weiter zu kommen.
Das ganze ändert sich nicht wenn das Fenster nur einen Teil des jeweiligen Monitors einnimmt.

**Comment by joshuajeschek** [comment]
richtig dummes workaround: fenster um 1 pixel verkleinern und wieder vergrößern
danke @Rotwolf

**Comment by joshuajeschek** [comment]
https://stackoverflow.com/questions/30824996/java-is-it-possible-to-disable-windows-dpi-scaling-from-within-java
windows high DPI scaling!

**Comment by Rotwolf** [comment]
element.getScene().getWindow().setWidth(element.getScene().getWidth() + 0.001);
Funktioniert so nicht.
element.setWidth(element.getWidth()-1)
Geht auch nicht.
Erst ab -16 wird der Inhalt wieder richtig zentriert.
Bei 
element.setWidth(element.getWidth()-16)
element.setWidth(element.getWidth()+16)
passiert aber wieder nichts...
Dabei ist mir aber aufgefallen:
primaryStage.setMaximized(false);
primaryStage.setMaximized(true);
und Umgekehrt funktioniert.
Warum genau weiß ich noch nicht.
Bin ich noch dran.
Ist zwar sehr ugly, aber wenigstens etwas.

**Comment by TheDarkDesync** [comment]
bei mir in der Analyse hat das funktioniert:
`Main.primaryStage.setWidth(Main.primaryStage.getWidth() + 0.0001f);`
`Main.primaryStage.setHeight(Main.primaryStage.getHeight() + 0.0001f);`

**Comment by joshuajeschek** [comment]
> bei mir in der Analyse hat das funktioniert: `Main.primaryStage.setWidth(Main.primaryStage.getWidth() + 0.0001f);` `Main.primaryStage.setHeight(Main.primaryStage.getHeight() + 0.0001f);`

das finde ich weird xd
naja, wir haben jetzt eine funktion und würden die gleich in absscene integrieren

**Comment by joshuajeschek** [comment]
Benutzer von 4k Bildschirmen werden dazu aufgefordert, die Kompatabilitätseinstellungen von Windows zu ändern.
4K auf Windows ist pain.
