### ISSUE TITLE
Versuchsbild in installierter Toolbox wird nicht angezeigt [ZoomMaps]

### ISSUE THREAD

**Issue by TheDarkDesync** [weichware10/toolbox#18]
+ Kein Versuchsbild in der installierten Toolbox

**Comment by TheDarkDesync** [comment]
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

**Comment by joshuajeschek** [comment]
da es nur in der installer version nicht funktioniert, kann es sein das dependencies im JVM image fehlen
wäre also ganz interessant zu wissen welche java packages sich um den SSL handshake kümmern / welche bei der saveImage() Funktion benötigt werden

**Comment by joshuajeschek** [comment]
https://www.baeldung.com/java-ssl-handshake-failures
versuchen SSL certificates / keys mit zu erstellen bei installation

**Comment by joshuajeschek** [comment]
Speichern der Fotos in Datenbank? Hinzufügen von `Image image` statt `String imageurl` in Configuration

**Comment by joshuajeschek** [comment]
```xml
<jvm.modules>javafx.media,javafx.controls,javafx.fxml,java.logging,java.sql,java.management,java.security.sasl,jdk.crypto.ec</jvm.modules>
```

Hinzufügen von `jdk.crypto.ec` löst das Problem
